[supervisord]
nodaemon=true
logfile=/dev/null
logfile_maxbytes=0

[program:apigateway]
command=dotnet /app/gateway/ApiGateway.dll
directory=/app/gateway
environment=ASPNETCORE_URLS="http://+:8080",ASPNETCORE_ENVIRONMENT="Production"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
autorestart=true
priority=30

[program:authservice]
command=dotnet /app/auth/AuthService.dll
directory=/app/auth
environment=ASPNETCORE_URLS="http://+:5001",ASPNETCORE_ENVIRONMENT="Production"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
autorestart=true
priority=10

[program:listingsservice]
command=dotnet /app/listings/ListingsService.dll
directory=/app/listings
environment=ASPNETCORE_URLS="http://+:5002",ASPNETCORE_ENVIRONMENT="Production"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
autorestart=true
priority=10

[program:notificationservice]
command=dotnet /app/notification/NotificationService.dll
directory=/app/notification
environment=ASPNETCORE_URLS="http://+:5006",ASPNETCORE_ENVIRONMENT="Production"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
autorestart=true
priority=10

[program:messagingservice]
command=dotnet /app/messaging/MessagingService.dll
directory=/app/messaging
environment=ASPNETCORE_URLS="http://+:5004",ASPNETCORE_ENVIRONMENT="Production"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
autorestart=true
priority=10

[program:paymentservice]
command=dotnet /app/payment/PaymentService.dll
directory=/app/payment
environment=ASPNETCORE_URLS="http://+:5005",ASPNETCORE_ENVIRONMENT="Production"
stdout_logfile=/dev/fd/1
stdout_logfile_maxbytes=0
stderr_logfile=/dev/fd/2
stderr_logfile_maxbytes=0
autorestart=true
priority=10
